<?xml version="1.0" encoding="utf-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://oss.oru.com/" elementFormDefault="unqualified" targetNamespace="http://oss.oru.com/" version="1.0">
<xs:element name="getElectricInfoByAccount" type="tns:getElectricInfoByAccount"/>
<xs:element name="getElectricInfoByAccountResponse" type="tns:getElectricInfoByAccountResponse"/>
<xs:element name="getElectricInfoByPremise" type="tns:getElectricInfoByPremise"/>
<xs:element name="getElectricInfoByPremiseResponse" type="tns:getElectricInfoByPremiseResponse"/>
<xs:element name="getElectricInfoByXYCoordinates" type="tns:getElectricInfoByXYCoordinates"/>
<xs:element name="getElectricInfoByXYCoordinatesResponse" type="tns:getElectricInfoByXYCoordinatesResponse"/>
<xs:element name="locateInNRGViewer" type="tns:locateInNRGViewer"/>
<xs:element name="locateInNRGViewerResponse" type="tns:locateInNRGViewerResponse"/>
<xs:element name="sendToNRG" type="tns:sendToNRG"/>
<xs:element name="sendToNRGResponse" type="tns:sendToNRGResponse"/>
<xs:complexType name="sendToNRG">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
      <xs:element minOccurs="0" name="arg1" type="xs:int"/>
      <xs:element minOccurs="0" name="arg2" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="sendToNRGResponse">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name="getElectricInfoByAccount">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getElectricInfoByAccountResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="tns:electricInfo"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="electricInfo">
    <xs:complexContent>
      <xs:extension base="tns:abstractBusinessObject">
        <xs:sequence>
          <xs:element minOccurs="0" name="circuit" type="xs:string"/>
          <xs:element minOccurs="0" name="code" type="xs:string"/>
          <xs:element minOccurs="0" name="hgridX" type="xs:int"/>
          <xs:element minOccurs="0" name="hgridY" type="xs:int"/>
          <xs:element name="involt" type="xs:double"/>
          <xs:element minOccurs="0" name="KVA1" type="xs:string"/>
          <xs:element minOccurs="0" name="KVA2" type="xs:string"/>
          <xs:element minOccurs="0" name="KVA3" type="xs:string"/>
          <xs:element minOccurs="0" name="ky_ba" type="xs:string"/>
          <xs:element minOccurs="0" name="ky_prem_no" type="xs:string"/>
          <xs:element minOccurs="0" name="phase" type="xs:string"/>
          <xs:element minOccurs="0" name="phase3" type="xs:string"/>
          <xs:element minOccurs="0" name="segment" type="xs:string"/>
          <xs:element minOccurs="0" name="service" type="xs:string"/>
          <xs:element minOccurs="0" name="servpoleX" type="xs:int"/>
          <xs:element minOccurs="0" name="servpoleY" type="xs:int"/>
          <xs:element minOccurs="0" name="tranGridX" type="xs:int"/>
          <xs:element minOccurs="0" name="tranGridY" type="xs:int"/>
          <xs:element minOccurs="0" name="transformer" type="xs:string"/>
          <xs:element minOccurs="0" name="transtype" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
<xs:complexType abstract="true" name="abstractBusinessObject">
    <xs:sequence>
      <xs:element minOccurs="0" name="partiality" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getElectricInfoByPremise">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getElectricInfoByPremiseResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="tns:electricInfo"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="locateInNRGViewer">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:int"/>
      <xs:element minOccurs="0" name="arg1" type="xs:int"/>
      <xs:element minOccurs="0" name="arg2" type="xs:int"/>
      <xs:element minOccurs="0" name="arg3" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="locateInNRGViewerResponse">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name="getElectricInfoByXYCoordinates">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
      <xs:element minOccurs="0" name="arg1" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getElectricInfoByXYCoordinatesResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="tns:electricInfo"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
