<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NuconWSService" targetNamespace="http://oss.oru.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://oss.oru.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://oss.oru.com/" schemaLocation="nuconws_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getElectricInfoByPremise">
    <wsdl:part name="parameters" element="tns:getElectricInfoByPremise">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getElectricInfoByAccount">
    <wsdl:part name="parameters" element="tns:getElectricInfoByAccount">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getElectricInfoByXYCoordinates">
    <wsdl:part name="parameters" element="tns:getElectricInfoByXYCoordinates">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getElectricInfoByXYCoordinatesResponse">
    <wsdl:part name="parameters" element="tns:getElectricInfoByXYCoordinatesResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getElectricInfoByAccountResponse">
    <wsdl:part name="parameters" element="tns:getElectricInfoByAccountResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sendToNRGResponse">
    <wsdl:part name="parameters" element="tns:sendToNRGResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sendToNRG">
    <wsdl:part name="parameters" element="tns:sendToNRG">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getElectricInfoByPremiseResponse">
    <wsdl:part name="parameters" element="tns:getElectricInfoByPremiseResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="locateInNRGViewerResponse">
    <wsdl:part name="parameters" element="tns:locateInNRGViewerResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="locateInNRGViewer">
    <wsdl:part name="parameters" element="tns:locateInNRGViewer">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="NuconWS">
    <wsdl:operation name="sendToNRG">
      <wsdl:input name="sendToNRG" message="tns:sendToNRG">
    </wsdl:input>
      <wsdl:output name="sendToNRGResponse" message="tns:sendToNRGResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByAccount">
      <wsdl:input name="getElectricInfoByAccount" message="tns:getElectricInfoByAccount">
    </wsdl:input>
      <wsdl:output name="getElectricInfoByAccountResponse" message="tns:getElectricInfoByAccountResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByPremise">
      <wsdl:input name="getElectricInfoByPremise" message="tns:getElectricInfoByPremise">
    </wsdl:input>
      <wsdl:output name="getElectricInfoByPremiseResponse" message="tns:getElectricInfoByPremiseResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="locateInNRGViewer">
      <wsdl:input name="locateInNRGViewer" message="tns:locateInNRGViewer">
    </wsdl:input>
      <wsdl:output name="locateInNRGViewerResponse" message="tns:locateInNRGViewerResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByXYCoordinates">
      <wsdl:input name="getElectricInfoByXYCoordinates" message="tns:getElectricInfoByXYCoordinates">
    </wsdl:input>
      <wsdl:output name="getElectricInfoByXYCoordinatesResponse" message="tns:getElectricInfoByXYCoordinatesResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NuconWSServiceSoapBinding" type="tns:NuconWS">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendToNRG">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="sendToNRG">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendToNRGResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByAccount">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getElectricInfoByAccount">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getElectricInfoByAccountResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByPremise">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getElectricInfoByPremise">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getElectricInfoByPremiseResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="locateInNRGViewer">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="locateInNRGViewer">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="locateInNRGViewerResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getElectricInfoByXYCoordinates">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="getElectricInfoByXYCoordinates">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getElectricInfoByXYCoordinatesResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NuconWSService">
    <wsdl:port name="NuconWSPort" binding="tns:NuconWSServiceSoapBinding">
      <soap12:address location="http://localhost:8080/nuconWS/services/NuconWSPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
